# Generated by Django 4.2.1 on 2023-06-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dadoshorta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmidadeSolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umidade', models.CharField(max_length=100)),
            ],
        ),
    ]
