# Generated by Django 4.1.7 on 2023-06-20 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dadoshorta', '0003_bomba_dadhoshorta_criado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadhoshorta',
            old_name='humidade',
            new_name='umidade',
        ),
    ]
