# Generated by Django 4.1.7 on 2023-06-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dadoshorta', '0004_rename_humidade_dadhoshorta_umidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadhoshorta',
            old_name='criado',
            new_name='Data',
        ),
    ]
