# Generated by Django 4.1.7 on 2023-06-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dadoshorta', '0005_rename_criado_dadhoshorta_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadhoshorta',
            old_name='Data',
            new_name='data',
        ),
    ]
