# Generated by Django 4.1.7 on 2023-07-04 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dadoshorta', '0006_rename_data_dadhoshorta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='umidadesolo',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
