# Generated by Django 4.1.7 on 2023-07-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dadoshorta', '0007_umidadesolo_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='BombaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
    ]
