# Generated by Django 4.1.7 on 2023-07-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dadoshorta', '0008_bombausuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='bombausuario',
            name='user',
            field=models.BooleanField(default=False),
        ),
    ]
