# Generated by Django 4.1.7 on 2023-07-06 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dadoshorta', '0009_bombausuario_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bombausuario',
            old_name='estado',
            new_name='bomba',
        ),
    ]
